### ISSUE TITLE
Need Your advice: Begin form baseqa or bioasqa

### ISSUE THREAD

**Issue by noyessie** [oaqa/baseqa#17]
> Please, excuse me but my english writing is not well. my question maybe stupid, but i need your help.

I want to make a question answering system for cyber security domain. I have got a small knowledge graph of cybersecurity domain and a big datasets of pdf files.

My question is that: ` what do you recommend me to do ? adapt from bioasq or from baseqa`

Now, I sereously learn bioasqa systems and i think, i understant the code logic and the pipeline process for answertype classification and he work fine. But i have a strong difficulty to continue on document/snippets/concepts retrieval , and answer generation. 

I think these part of bioasq pipeline is hardly adapted to Bioasq challenge and the different algorithms you use here is adapted to BioASQ dataset. It is correct ??

@ziy I read your publications and your thesis. But, It remains flour.

Please one advice.

Thank in advance.

**Comment by ziy** [comment]
See https://github.com/oaqa/bioasq/issues/4
