### ISSUE TITLE
OAQA, BASEQA + DUCC(Distributed UIMA Cluster Computing)

### ISSUE THREAD

**Issue by noyessie** [oaqa/baseqa#18]
BaseQA need so much ram and processor to run. I want to use it like a distributed application, but i don't know the impact of the usage of uima-ecd.

This is my question: 

- Do you think it is possible to convert ecd/cse application to DUCC easily ?
- If yes, Why did not you do that?
- Are there any other solution to use uima ecd/cse as distributed application ?

Thank's in advance.

**Comment by ziy** [comment]
First, I heard about DUCC but I don’t have too much experience with it, so I can’t estimate whether the conversion is easy or not. Please note that UIMA-ECD project started in 2011 when there was no publicly released DUCC at that time.

-- 
Zi Yang
Recent Ph.D. Graduate
Language Technologies Institute
School of Computer Science
Carnegie Mellon University
HP: http://www.cs.cmu.edu/~ziy <http://www.cs.cmu.edu/~ziy>

**Comment by noyessie** [comment]
Thanks
